algamoney:
  seguranca:
    enable-https: true
  origin-permitida: https://algamoney-curso.herokuapp.com/
 
spring:
  datasource:
    password: nordsmho6jxlwx0n
    url: jdbc:mysql://mgs0iaapcj3p9srz.cbetxkdyhwsb.us-east-1.rds.amazonaws.com/qfi62dk073k59ve9
    username: m6ztl17yomaj2gtc  
