spring:
  profiles:
    active: oauth-security
#    active: basic-security
  datasource:
    url: jdbc:mysql://localhost/algamoneyapi?createDatabaseIfNotExist=true&useSSL=false&useTimezone=true&serverTimezone=America/Sao_Paulo  
    username: root
    password: root
  jackson:
    date-format: yyyy-MM-dd
    deserialization:
      fail-on-unknown-properties: true
  jpa:
    database: MYSQL
    show-sql: true
  flyway:
    enabled: false