spring:
  profiles:
#    active: basic-security
    active: oauth-security
  datasource:
    url: jdbc:mysql://localhost/algamoneyapi?createDatabaseIfNotExist=true&useSSL=false&useTimezone=true&serverTimezone=America/Sao_Paulo  
    username: root
    password: root
  jackson:
    date-format: yyyy-MM-dd
    deserialization:
      fail-on-unknown-properties: true
  jpa:
    database: MYSQL
    show-sql: true
    open-in-view: true
  flyway:
    enabled: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-request-size: 15MB
      max-file-size: 15MB
algamoney:  origem-permitida: http://localhost:4200
#  origem-permitida: http://www.algamoney.holanda.eti.br
#  origem-permitida: https://algamoney-ui-curso.herokuapp.com
logging:
  level:
    com.algaworks.algamoney.api: DEBUG